# Generated by Django 4.2.27 on 2026-10-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostilealliance',
            name='is_friendly',
            field=models.BooleanField(default=False, help_text='Flagged as friendly / allied entity (ignored by threat scanner & hostile intel)'),
        ),
        migrations.AddField(
            model_name='hostilecorporation',
            name='is_friendly',
            field=models.BooleanField(default=False, help_text='Flagged as friendly / allied entity (ignored by threat scanner & hostile intel)'),
        ),
        migrations.AddField(
            model_name='hostilepilotdossier',
            name='alliance_ticker',
            field=models.CharField(blank=True, help_text='Alliance ticker (e.g. FIGL)', max_length=16),
        ),
        migrations.AddField(
            model_name='hostilepilotdossier',
            name='birthday',
            field=models.DateField(blank=True, help_text='Character creation date', null=True),
        ),
        migrations.AddField(
            model_name='hostilepilotdossier',
            name='corporation_ticker',
            field=models.CharField(blank=True, help_text='Corporation ticker (e.g. STHCM)', max_length=16),
        ),
        migrations.AddField(
            model_name='hostilepilotdossier',
            name='danger_ratio',
            field=models.IntegerField(blank=True, default=0, help_text='zKillboard Danger Ratio (0-100%)'),
        ),
        migrations.AddField(
            model_name='hostilepilotdossier',
            name='gang_ratio',
            field=models.IntegerField(blank=True, default=0, help_text='zKillboard Gang Ratio (0-100%)'),
        ),
        migrations.AddField(
            model_name='hostilepilotdossier',
            name='likely_ship',
            field=models.CharField(blank=True, help_text='Primary / most likely flown ship', max_length=128),
        ),
        migrations.AddField(
            model_name='hostilepilotdossier',
            name='security_status',
            field=models.FloatField(blank=True, help_text='Character security status (-10.0 to 10.0)', null=True),
        ),
        migrations.AddField(
            model_name='hostilepilotdossier',
            name='top_ships',
            field=models.JSONField(blank=True, default=list, help_text='Top flown ship hulls'),
        ),
    ]
