"""
EFT Fitting Parser and Exporter utilizing django-sde / eve_sde
"""

# Standard Library
import re
from typing import Any, Dict, List, Optional, Tuple

# Third Party
from eve_sde.models import ItemType, TypeEffect

# AA Hostile Intel
from hostile.models import HostileStructure, StructureFitting, StructureModule

SLOT_HIGH = "HIGH"
SLOT_MED = "MED"
SLOT_LOW = "LOW"
SLOT_RIG = "RIG"
SLOT_SERVICE = "SERVICE"
SLOT_CHARGE = "CHARGE"

# Common CCP Dogma Effect IDs for slots
DOGMA_EFFECT_HI = 12
DOGMA_EFFECT_MED = 13
DOGMA_EFFECT_LO = 11
DOGMA_EFFECT_RIG = 2663
DOGMA_EFFECT_SERVICE = 6306

# Regex patterns for ship scanner structure fitting slot headers
SLOT_HEADER_PATTERNS = {
    SLOT_HIGH: re.compile(
        r"^\[?\s*(?:Hi|High)(?:\s*|-)?(?:Power\s+)?Slots?\s*\]?:?$", re.IGNORECASE
    ),
    SLOT_MED: re.compile(
        r"^\[?\s*(?:Med|Medium|Mid)(?:\s*|-)?(?:Power\s+)?Slots?\s*\]?:?$", re.IGNORECASE
    ),
    SLOT_LOW: re.compile(
        r"^\[?\s*(?:Lo|Low)(?:\s*|-)?(?:Power\s+)?Slots?\s*\]?:?$", re.IGNORECASE
    ),
    SLOT_SERVICE: re.compile(
        r"^\[?\s*(?:Structure\s+)?(?:Service\s+Slots?|Services|Service|Service\s+Modules?)\s*\]?:?$",
        re.IGNORECASE,
    ),
    SLOT_RIG: re.compile(
        r"^\[?\s*(?:Structure\s+)?(?:Rig\s+Slots?|Rigs|Rig|Structure\s+Rigs)\s*\]?:?$",
        re.IGNORECASE,
    ),
    SLOT_CHARGE: re.compile(
        r"^\[?\s*(?:Charge\s+Slots?|Charges|Charge|Ammo|Fighter\s+Bay|Fighter\s+Slots?|Fighters|Fighter|Drone\s+Bay|Drones|Loaded\s+Charges)\s*\]?:?$",
        re.IGNORECASE,
    ),
}


def match_slot_header(line: str) -> Optional[str]:
    """Matches a line against known slot section header patterns (e.g. 'High Power Slots')"""
    clean = line.strip()
    for slot_key, pattern in SLOT_HEADER_PATTERNS.items():
        if pattern.match(clean):
            return slot_key
    return None


class StructureFittingParser:
    """
    Parser for structure fittings generated by ship scanner results, inspect windows, or EFT formatting.
    Accurately maps High, Medium, Low, Rig, and Service slots.
    """

    @classmethod
    def match_slot_header(cls, line: str) -> Optional[str]:
        return match_slot_header(line)

    @classmethod
    def is_structure_fitting(cls, text: str) -> bool:
        """Determines if the text contains structure fitting slot headers or Standup modules"""
        if not text:
            return False
        clean_lines = [l.strip() for l in text.strip().splitlines() if l.strip()]
        if not clean_lines:
            return False

        header_matches = sum(1 for l in clean_lines if cls.match_slot_header(l))
        if header_matches >= 1:
            return True

        standup_count = sum(1 for l in clean_lines if "standup" in l.lower())
        if standup_count >= 2:
            return True

        return False

    @classmethod
    def resolve_slot_type(cls, item_type: ItemType) -> str:
        """Determines the slot type of an item using Dogma effects, group taxonomy, and naming patterns"""
        if not item_type:
            return SLOT_MED

        # Check Dogma effects if available in SDE
        try:
            effects = set(
                TypeEffect.objects.filter(item_type=item_type).values_list("dogma_effect_id", flat=True)
            )
            if DOGMA_EFFECT_SERVICE in effects:
                return SLOT_SERVICE
            if DOGMA_EFFECT_HI in effects:
                return SLOT_HIGH
            if DOGMA_EFFECT_MED in effects:
                return SLOT_MED
            if DOGMA_EFFECT_LO in effects:
                return SLOT_LOW
            if DOGMA_EFFECT_RIG in effects:
                return SLOT_RIG
        except Exception:
            pass

        group_name = ""
        category_name = ""
        if hasattr(item_type, "group") and item_type.group:
            group_name = item_type.group.name or ""
            if hasattr(item_type.group, "category") and item_type.group.category:
                category_name = item_type.group.category.name or ""

        # Service module checks
        if "Service" in group_name or "Service" in category_name or "Standup Service" in item_type.name:
            return SLOT_SERVICE

        # Rig checks
        if "Rig" in group_name or "Rig" in category_name:
            return SLOT_RIG

        # Charges & Fighters
        if (
            category_name in ["Charge", "Fighter", "Drone"]
            or "Fighter" in group_name
            or "Charge" in group_name
            or "Script" in group_name
            or "Nanite" in group_name
        ):
            return SLOT_CHARGE

        name_lower = item_type.name.lower()

        # High slot naming signatures
        high_signatures = [
            "launcher",
            "neutralizer",
            "nosferatu",
            "beam",
            "laser",
            "turret",
            "autocannon",
            "artillery",
            "railgun",
            "blaster",
            "point defense",
            "smartbomb",
            "doomsday",
            "guided bomb",
            "missile",
            "torpedo",
            "pulse",
            "canceller",
            "cyno",
            "burst projector",
            "energy neutralizer",
        ]
        if any(sig in name_lower for sig in high_signatures):
            return SLOT_HIGH

        # Low slot signatures
        low_signatures = [
            "damage control",
            "ballistic control",
            "heat sink",
            "magnetic field stabilizer",
            "gyrostabilizer",
            "power diagnostic",
            "reactor unit",
            "armor plate",
            "armor repairer",
            "armor hardener",
            "coating",
            "membrane",
            "energized",
            "reinforcement",
            "overdrive",
            "nanofiber",
            "inertial",
            "signal amplifier",
            "warp core stabilizer",
            "co-processor",
        ]
        if any(sig in name_lower for sig in low_signatures):
            return SLOT_LOW

        # Mid slot signatures
        med_signatures = [
            "shield",
            "target painter",
            "sensor booster",
            "ecm",
            "sensor dampener",
            "tracking computer",
            "guidance computer",
            "warp scrambler",
            "warp disruptor",
            "stasis web",
            "grappler",
            "cap battery",
            "cap recharger",
            "cap booster",
            "propulsion",
            "afterburner",
            "microwarpdrive",
        ]
        if any(sig in name_lower for sig in med_signatures):
            return SLOT_MED

        return SLOT_MED

    @classmethod
    def parse(cls, text: str) -> Dict[str, Any]:
        """
        Parses ship scanner structure fitting text or EFT text into structured fitting dictionary.
        Recognizes slot headers (High Power Slots, Medium Power Slots, Low Power Slots, Service Slots, Rig Slots).
        """
        lines = [line.strip() for line in text.strip().splitlines() if line.strip()]
        if not lines:
            return {
                "hull_type_name": "",
                "fitting_name": "",
                "hull_item_type": None,
                "slots": {
                    SLOT_HIGH: [],
                    SLOT_MED: [],
                    SLOT_LOW: [],
                    SLOT_RIG: [],
                    SLOT_SERVICE: [],
                    SLOT_CHARGE: [],
                },
                "raw_items": [],
                "errors": ["Empty fitting string provided"],
            }

        hull_name = ""
        fit_name = ""
        module_lines = lines

        # Check if first line is standard EFT header: [Hull, FitName]
        first_line = lines[0]
        if not cls.match_slot_header(first_line):
            header_match = re.match(r"^\[(.*?)\]$", first_line)
            if header_match:
                header_content = header_match.group(1)
                parts = [p.strip() for p in header_content.split(",", 1)]
                hull_name = parts[0]
                if len(parts) > 1:
                    fit_name = parts[1]
                module_lines = lines[1:]

        hull_item_type = None
        if hull_name:
            hull_item_type = ItemType.objects.filter(name__iexact=hull_name).first()

        slots: Dict[str, List[Dict[str, Any]]] = {
            SLOT_HIGH: [],
            SLOT_MED: [],
            SLOT_LOW: [],
            SLOT_RIG: [],
            SLOT_SERVICE: [],
            SLOT_CHARGE: [],
        }
        raw_items: List[str] = []
        errors: List[str] = []

        current_slot_header: Optional[str] = None

        for line in module_lines:
            if not line or line.startswith("#"):
                continue

            # Check if this line is a slot header like 'High Power Slots' or 'Medium Power Slots'
            matched_header = cls.match_slot_header(line)
            if matched_header:
                current_slot_header = matched_header
                continue

            # Skip placeholder empty slots (e.g. '[Empty High slot]', 'Empty', '-Empty-')
            if re.match(r"^\[?Empty(?:\s+\w+)?(?:\s+slot)?\]?$", line, re.I) or line.lower() in ["empty", "-empty-", "none"]:
                continue

            # Strip quantity or charge loaded (e.g. 'Standup Anticapital Missile Launcher I x2' or 'Standup Guided Bomb Launcher I, Standup Guided Bomb')
            item_raw = line
            charge_raw = None

            if "," in item_raw:
                parts = [p.strip() for p in item_raw.split(",", 1)]
                item_raw = parts[0]
                charge_raw = parts[1]
            elif "\t" in item_raw:
                parts = [p.strip() for p in item_raw.split("\t", 1)]
                item_raw = parts[0]
                if len(parts) > 1 and parts[1]:
                    charge_raw = parts[1]

            # Check bracketed scripts/charges e.g. 'Standup Focused Warp Disruptor I [Focused Warp Disruptor Script]'
            bracket_charge = re.search(r"\[(.*?)\]$", item_raw)
            if bracket_charge and not item_raw.startswith("["):
                charge_raw = bracket_charge.group(1).strip()
                item_raw = item_raw[: bracket_charge.start()].strip()

            # Remove multiplier prefixes e.g. "2x Standup Launcher"
            qty = 1
            prefix_match = re.match(r"^(\d+)\s*[xX]\s+(.+)$", item_raw)
            if prefix_match:
                qty = int(prefix_match.group(1))
                item_raw = prefix_match.group(2).strip()

            # Remove multiplier suffixes e.g. "x10", "x 5", "(2)", "[2]"
            qty_match = re.search(r"\s+x\s*(\d+)$", item_raw, re.I)
            if qty_match:
                qty = int(qty_match.group(1))
                item_raw = item_raw[: qty_match.start()].strip()
            else:
                paren_match = re.search(r"\s*\((?:x\s*)?(\d+)\)$", item_raw, re.I)
                if paren_match:
                    qty = int(paren_match.group(1))
                    item_raw = item_raw[: paren_match.start()].strip()

            raw_items.append(item_raw)
            item_type = ItemType.objects.filter(name__iexact=item_raw).first()

            if not item_type:
                # Try prefix/contains search if exact match fails
                item_type = ItemType.objects.filter(name__icontains=item_raw).first()

            # If inside an explicit slot header section (High Power Slots, Service Slots, etc.), respect that header
            if current_slot_header:
                slot_type = current_slot_header
            elif item_type:
                slot_type = cls.resolve_slot_type(item_type)
            else:
                slot_type = SLOT_MED

            for _ in range(qty):
                slot_entry = {
                    "module_name": item_type.name if item_type else item_raw,
                    "item_type": item_type,
                    "type_id": item_type.id if item_type else None,
                    "slot_type": slot_type,
                    "is_online": True,
                }
                slots[slot_type].append(slot_entry)

            if charge_raw:
                charge_type = ItemType.objects.filter(name__iexact=charge_raw).first()
                if not charge_type:
                    charge_type = ItemType.objects.filter(name__icontains=charge_raw).first()
                slots[SLOT_CHARGE].append(
                    {
                        "module_name": charge_type.name if charge_type else charge_raw,
                        "item_type": charge_type,
                        "type_id": charge_type.id if charge_type else None,
                        "slot_type": SLOT_CHARGE,
                        "is_online": True,
                    }
                )

        # Hull inference from modules if hull_name is absent
        if not hull_item_type and not hull_name:
            if any(re.search(r"\b(Anticapital|XL|Superheavy|Doomsday|Burst Projector)\b", m, re.I) for m in raw_items):
                hull_name = "Keepstar"
                hull_item_type = ItemType.objects.filter(name__iexact="Keepstar").first()
            elif any("standup" in m.lower() for m in raw_items):
                hull_name = "Structure"
                hull_item_type = ItemType.objects.filter(name__iexact="Citadel").first() or ItemType.objects.filter(name__iexact="Astrahus").first()

        return {
            "hull_type_name": hull_name,
            "fitting_name": fit_name,
            "hull_item_type": hull_item_type,
            "slots": slots,
            "raw_items": raw_items,
            "errors": errors,
        }

    @classmethod
    def export_eft(cls, fitting: StructureFitting) -> str:
        """Exports a StructureFitting model instance to an EFT string"""
        structure = fitting.structure
        hull_name = structure.structure_type.name if structure.structure_type else "Structure"
        fit_name = fitting.name or structure.name or "Intel Fit"

        lines = [f"[{hull_name}, {fit_name}]"]

        modules = fitting.modules.select_related("module_type").order_by("slot_type", "slot_number")

        slots_order = [SLOT_LOW, SLOT_MED, SLOT_HIGH, SLOT_RIG, SLOT_SERVICE, SLOT_CHARGE]
        grouped: Dict[str, List[StructureModule]] = {s: [] for s in slots_order}

        for mod in modules:
            if mod.slot_type in grouped:
                grouped[mod.slot_type].append(mod)

        for slot_key in slots_order:
            mod_list = grouped[slot_key]
            if mod_list:
                for m in mod_list:
                    lines.append(m.module_type.name)
                lines.append("")

        return "\n".join(lines).strip()


class EFTParser(StructureFittingParser):
    """Alias for backwards compatibility and generic EFT parsing"""
    parse_eft = StructureFittingParser.parse
